### ISSUE TITLE
PvP model for networking?

### ISSUE THREAD

**Issue by Cleroth** [GameSparks/gamesparks-docs#1]
```
Host Server Support for Player vs. Player (PvP) Model. We use a PvP model for our network programming. However, we use a host server to relay communications between players and deliver important benefits:

Supports a higher number of players than traditional PvP models.
Gives you the option to host games in the regions of your choice to reduce latency issues.
```

Who the hell wrote this? This means absolutely nothing.

**Comment by cjbonn** [comment]
How about you suggest a change instead of just complaining?

**Comment by Cleroth** [comment]
Ah, yes. "Why don't you suggest a change to improve our product for free, so we can charge you to use it, but then ignore your change anywhere because we couldn't hire someone to write about our product who actually knows about our product."

Watch how your pull request will stay open for the next few years.

**Comment by cjbonn** [comment]
Considering I have no issues with the current synopsis that is all it is trying to provide, this is all on your m8.

And I've already had many pull requests resolved last couple weeks.
